### ISSUE TITLE
Want to add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by lazyfuhrer** [gita/gita#27]
### What would you like to share?

I want to add a CONTRIBUTING.md file. It will help the contributors to abide by the guidelines of contributing to any open source project. Please assign the issue to me.

**Comment by Kaushalrr006** [comment]
Please assign me this task i am intrested in it

**Comment by Dasika-Vaishnavi** [comment]
I am interested in doing this task, hoping I can still contribute!

**Comment by lazyfuhrer** [comment]
Yes
